name: AI Code Review

on:
  issue_comment:
    types: [created]

jobs:
  ai-review:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/review') }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Get Repository Name
        id: get-repository-name
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const shouldRun = repo !== 'main';
            
            console.log(`Repository name is ${repo}, should run is ${shouldRun}`);
            
            return { shouldRun: shouldRun }
          result-encoding: string

      - uses: actions/github-script@v7
        if: ${{ fromJson(steps.get-repository-name.outputs.result).shouldRun }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })